input {
  file {
    path => "/odoo.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} %{NUMBER:pid} %{LOGLEVEL:level} %{DATA:db} %{DATA:logger}: %{GREEDYDATA:msg}"
    }
  }
  date {
    match => ["timestamp", "ISO8601"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "odoo-logs-%{+YYYY.MM.dd}"
  }
}